### ISSUE TITLE
lost checkbox with portrait orientation image of an answer

### ISSUE THREAD

**Issue by LennyLip** [studyhub-co/physics-is-beautiful#108]
![editor](https://user-images.githubusercontent.com/955994/42506009-42a15460-8449-11e8-9eff-f204a6564ed3.png)

**Comment by nscozzaro** [comment]
(Low priority)
At the highest level, I want to make the curriculum editor similar to Google Slides/Microsoft Powerpoint. What I mean by that is problem types will be templates, but the user can modify those templates. There should be tools so the user can add formatting, e.g. italics, alignment, spacing, and math helpers, be able to add (multiple) images, videos, etc. There should even be a way to import powerpoint slides somehow. We will also want a version control feature so that we can undo changes. 

But the improvements we can make for now:

- [ ] If you try and upload image filetypes like an SVG it throws an error in the console presumably because it's not an allowed type. We should update the model to allow SVG's and more image types, and prevent the user from uploading other image types or convey to the user that the image type was not allowed
- [ ] Update the curriculum editor so that the CSS is identical as in the student view, including the checkboxes and radio button. (I'm thinking we should have a shared CSS file for this? Where would that file live? Probably in the root static folder)
- [ ] We should also add X's to be able to delete the image without deleting the text, or the other way around. 
- [ ] Increase the allowed length of the question text + hint and handle errors if the text is too long. Also make the box larger so that you can always see the entire text while editing. 
- [ ] The Mathematical Expression math box is having issues... try adding spaces or something like \alpha and then click off the box... then delete the alpha. If it shows the black border after editing the box it means something is wrong
- [ ] Place the hint above the placeholder image, and make the placeholder image smaller

**Comment by LennyLip** [comment]
Closed due Sandbox Editor version will release.
